from backend.app.schemas.common import ApiResponse, PaginatedResponse, PaginationParams
from backend.app.schemas.auth import (
    RegisterStudentRequest,
    RegisterFacultyRequest,
    LoginRequest,
    TokenResponse,
    TokenData,
)
from backend.app.schemas.user import (
    UserResponse,
    StudentProfileResponse,
    FacultyProfileResponse,
    UpdateStudentProfileRequest,
    UpdateFacultyProfileRequest,
    FacultyVerificationRequest,
)
from backend.app.schemas.college import (
    CollegeResponse,
    CreateCollegeRequest,
    AnnouncementResponse,
    CreateAnnouncementRequest,
)
from backend.app.schemas.note import (
    NoteResponse,
    CreateNoteRequest,
    UpdateNoteRequest,
    PDFNoteResponse,
)
from backend.app.schemas.video import VideoResponse, CreateVideoRequest, UpdateVideoRequest
from backend.app.schemas.quiz import (
    CreateQuestionRequest,
    QuestionForStudentResponse,
    QuestionForFacultyResponse,
    CreateQuizRequest,
    QuizResponse,
    QuizDetailForStudentResponse,
    QuizDetailForFacultyResponse,
    StartQuizAttemptResponse,
    SubmitQuizRequest,
    QuizAttemptResultResponse,
)
from backend.app.schemas.assignment import (
    AssignmentResponse,
    CreateAssignmentRequest,
    SubmitAssignmentRequest,
    EvaluateAssignmentRequest,
    AssignmentSubmissionResponse,
)
from backend.app.schemas.coding import (
    CodingProblemResponse,
    CreateCodingProblemRequest,
    ExecuteCodeRequest,
    ExecutionResultResponse,
    SubmitCodeRequest,
    SubmissionResultResponse,
)
from backend.app.schemas.interview import (
    InterviewResponse,
    CreateInterviewRequest,
    InterviewQuestionResponse,
    InterviewEvaluationRequest,
    InterviewResultResponse,
    VideoSessionResponse,
    WebRTCSignalingMessage,
)
from backend.app.schemas.notification import NotificationResponse, MarkNotificationReadRequest
from backend.app.schemas.progress import (
    TopicProgressResponse,
    StudentStatsResponse,
    FacultyStudentPerformanceItem,
    FacultyDashboardStatsResponse,
)
from backend.app.schemas.community import CommunityContentItemResponse, CommunityFilterParams

__all__ = [
    "ApiResponse",
    "PaginatedResponse",
    "PaginationParams",
    "RegisterStudentRequest",
    "RegisterFacultyRequest",
    "LoginRequest",
    "TokenResponse",
    "TokenData",
    "UserResponse",
    "StudentProfileResponse",
    "FacultyProfileResponse",
    "UpdateStudentProfileRequest",
    "UpdateFacultyProfileRequest",
    "FacultyVerificationRequest",
    "CollegeResponse",
    "CreateCollegeRequest",
    "AnnouncementResponse",
    "CreateAnnouncementRequest",
    "NoteResponse",
    "CreateNoteRequest",
    "UpdateNoteRequest",
    "PDFNoteResponse",
    "VideoResponse",
    "CreateVideoRequest",
    "UpdateVideoRequest",
    "CreateQuestionRequest",
    "QuestionForStudentResponse",
    "QuestionForFacultyResponse",
    "CreateQuizRequest",
    "QuizResponse",
    "QuizDetailForStudentResponse",
    "QuizDetailForFacultyResponse",
    "StartQuizAttemptResponse",
    "SubmitQuizRequest",
    "QuizAttemptResultResponse",
    "AssignmentResponse",
    "CreateAssignmentRequest",
    "SubmitAssignmentRequest",
    "EvaluateAssignmentRequest",
    "AssignmentSubmissionResponse",
    "CodingProblemResponse",
    "CreateCodingProblemRequest",
    "ExecuteCodeRequest",
    "ExecutionResultResponse",
    "SubmitCodeRequest",
    "SubmissionResultResponse",
    "InterviewResponse",
    "CreateInterviewRequest",
    "InterviewQuestionResponse",
    "InterviewEvaluationRequest",
    "InterviewResultResponse",
    "VideoSessionResponse",
    "WebRTCSignalingMessage",
    "NotificationResponse",
    "MarkNotificationReadRequest",
    "TopicProgressResponse",
    "StudentStatsResponse",
    "FacultyStudentPerformanceItem",
    "FacultyDashboardStatsResponse",
    "CommunityContentItemResponse",
    "CommunityFilterParams",
]
